module.exports = {
  theme: {
    screens: {
      sm: { max: '768px' },
      md: { min: '768.02px' },
      lg: { min: '992px' },
    },
    colors: {
      red1: '#D3382F',
      red2: '#FF4438',
      red3: '#FF8E87',
      red4: '#FFD3CD',
      red5: '#FFF2F1',
      gray1: '#313140',
      gray2: '#515164',
      gray3: '#9C9CAC',
      gray4: '#9C9CAC',
      gray5: '#E5E8ED',
      gray6: '#F5F6F9',
      gray7: '#f8f8fc',
      gray8: '#f7f7fa',
      gray9: '#d9d9d9',
      secondary1: '#313140',
      secondary2: '#515164',
      secondary3: '#9C9CAC',
      secondary4: '#E5E8ED',
      secondary5: '#F5F6F9',
      bg1: '#F5F6F9',
      bg2: '#ffffff',
      bg3: '#F5F6F9',
      // cyan1: '#009897',
      // cyan2: '#00BFBD',
      // cyan3: '#4CD1D0',
      // cyan4: '#B2ECEB',
      // cyan5: '#F2FCFC',
      // cyan6: '#00BFBD',
      // cyan7: '#0098A1',
      warning: '#FFC400',
      error: '#D3382F',
      info: '#00B3BD',
      success: '#0DE298',
      white: '#ffffff',
      black: '#000000',
      black1: '#002649',
      blackmask: 'rgba(0, 0, 0, 0.6)',
      special4: '#59779A',
      yellow1: '#EDFF41',
      transparent: 'transparent',
      current: 'currentColor',
      green1: '#E7FCF5',
    },
    fontSize: {
      xs: '10px',
      tiny: '12px',
      sm: '14px',
      base: '16px',
      lg: '20px',
      xl: '24px',
      '2xl': '32px',
      '3xl': '40px',
      '4xl': '48px',
    },
    spacing: {
      0: '0',
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      13: '52px',
      14: '56px',
      15: '60px',
      16: '64px',
      18: '72px',
      20: '80px',
      24: '96px',
      26: '104px',
      30: '120px',
      37: '148px',
      full: '100%',
      '1/3': '33.33333%',
    },
    boxShadow: {
      panel: 'none',
      hover: '0px 5px 14px rgba(0, 40, 117, 0.05)',
      popup: '0px 5px 14px rgba(0, 40, 117, 0.05)',
      'all-around': '0px 0px 14px rgba(0, 40, 117, 0.1)',
    },
    backgroundColor: (theme) => ({
      ...theme('colors'),
      dark: '#282829',
    }),
    extend: {
      height: {
        45: '180px',
        50: '200px',
      },
      width: {
        50: '200px',
        70: '300px',
        75: '360px',
        125: '500px',
        '936px': '936px',
        '300px': '300px',
        '480px': '480px',
        '800px': '800px',
        '7/10': '70%',
      },
      maxWidth: {
        'grid-12': '1176px',
        'grid-10': '984px',
        'grid-8': '768px',
        'grid-6': '576px',
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        full: '100%',
        '100vw': '100vw',
      },
      flex: {
        2: '2 1 0%',
        3: '3 1 0%',
      },
      minHeight: {
        6: '24px',
        10: '40px',
        15: '60px',
        25: '100px',
        50: '200px',
        75: '300px',
        100: '400px',
      },
      borderRadius: {
        DEFAULT: '8px',
        dot5: '4px',
        1: '8px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        100: '100%',
      },
      inset: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        14: '56px',
        16: '64px',
        18: '72px',
        20: '80px',
        24: '96px',
        '1/4': '25%',
        '1/3': '33.33333%',
        '1/2': '50%',
        full: '100%',
      },
      zIndex: {
        5: 5,
        100: 100,
      },
      lineHeight: {
        3: '12px',
        4: '16px',
        5: '20px',
        '11/2': '22px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        12: '48px',
        14: '56px',
        '5dot5': '22px',
        '4dot5': '18px',
      },
      transitionDuration: {
        400: '400ms',
        1500: '1500ms',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
    container: false,
    space: false,
    divideWidth: false,
    divideColor: false,
    divideOpacity: false,
    accessibility: false,
    appearance: false,
    backgroundAttachment: false,
    // backgroundColor: false,
    // backgroundOpacity: false,
    // backgroundPosition: false,
    // backgroundRepeat: false,
    // backgroundSize: false,
    // borderCollapse: false,
    // borderColor: false,
    // borderOpacity: false,
    // borderRadius: false,
    // borderStyle: false,
    // borderWidth: false,
    boxSizing: false,
    // cursor: false,
    // display: false,
    // flexDirection: false,
    // flexWrap: false,
    // alignItems: false,
    // alignSelf: false,
    // justifyContent: false,
    // alignContent: false,
    // flex: false,
    // flexGrow: false,
    // flexShrink: false,
    order: false,
    float: false,
    clear: false,
    fontFamily: false,
    // fontWeight: false,
    // height: false,
    // fontSize: false,
    // lineHeight: false,
    // listStylePosition: false,
    // listStyleType: false,
    // margin: false,
    // maxHeight: false,
    // maxWidth: false,
    // minHeight: false,
    // minWidth: false,
    // objectFit: false,
    objectPosition: false,
    // opacity: false,
    // outline: false,
    // overflow: false,
    // padding: false,
    // placeholderColor: false,
    placeholderOpacity: false,
    pointerEvents: false,
    // position: false,
    // inset: false,
    resize: false,
    // boxShadow: false,
    // fill: false,
    // stroke: false,
    strokeWidth: false,
    tableLayout: false,
    // textAlign: false,
    // textColor: false,
    textOpacity: false,
    // fontStyle: false,
    // textTransform: false,
    // textDecoration: false,
    fontSmoothing: false,
    letterSpacing: false,
    // userSelect: false,
    // verticalAlign: false,
    // visibility: false,
    // whitespace: false,
    // wordBreak: false,
    // width: false,
    // zIndex: false,
    gap: false,
    gridAutoFlow: false,
    gridTemplateColumns: false,
    gridColumn: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridTemplateRows: false,
    gridRow: false,
    gridRowStart: false,
    gridRowEnd: false,
    // transform: false,
    // transformOrigin: false,
    // scale: false,
    // rotate: false,
    // translate: false,
    skew: false,
    // transitionProperty: false,
    // transitionTimingFunction: false,
    // transitionDuration: false,
    transitionDelay: false,
  },
};
